# 工作流名称
name: hexo-deploy-ci

# 控制工作流的生效条件，这里设置为 分支 master 有新的推送时触发
on:
  push:
    branches:
      - master

# 条件生效后要执行的任务
jobs:
  # 这里是单个任务
  build:
    # 任务的执行类型
    runs-on: ubuntu-latest

    # 任务执行步骤
    steps:
      # 检出仓库分支
      - name: Checkout Repository master branch
        uses: actions/checkout@v2

      # 指定 Node 版本
      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      
      # 安装代码需要的依赖
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install
      
      # 利用 hexo 生成静态页面
      - name: Generate Page
        run: |
          hexo g
      
      # 使用 rsync 将 public 文件夹传输至至服务器
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
          switches: -avzr --delete
          # 要同步的文件夹
          path: public/
          # 服务器传输至的目录，上文中的 /home/baoxuebin/my-hexo-project/public
          remote_path: /home/baoxuebin/my-hexo-project/public
          remote_host: 81.69.252.147
          remote_user: root
          # 密钥作为敏感信息，请勿直接使用；可以在 Github 仓库页面>>Settings>>secrets 添加
          remote_key: ${{ secrets.TENCENT_CLOUD_PRIVATE_KEY }}